import { LICENSE_SERVER_URL, REMOTE_URL, REMOTE_WSS_URL } from './loadConfig';

export const SERVER_PORTS = {
  BACKEND_PORT: 3000,
  STRATEGY_ANALYZER_PORT: 3002,
  POSITION_MANAGER_PORT: 3003,
  DATA_FILLERS_PORT: 3004,
  MARKETS_MONITOR_PORT: 3005,
  NOTIFICATIONS_SYSTEM_PORT: 3006,
  LIVE_BOT_PORT: 3007,
  CENTRALIZATION_PORT: 8000,
};

export const PROJECT_URLS = {
  BACKEND_URL: REMOTE_URL + ':' + SERVER_PORTS.BACKEND_PORT,
  BACKEND_WEBSOCKET: REMOTE_WSS_URL + ':' + SERVER_PORTS.BACKEND_PORT + '/ws',
  STRATEGY_ANALYZER_URL: REMOTE_URL + ':' + SERVER_PORTS.STRATEGY_ANALYZER_PORT,
  POSITION_MANAGER_URL: REMOTE_URL + ':' + SERVER_PORTS.POSITION_MANAGER_PORT,
  CENTRALIZATION_URL: 'centralization.' + REMOTE_URL,
  DATA_FILLERS_URL: REMOTE_URL + ':' + SERVER_PORTS.DATA_FILLERS_PORT,
  MARKETS_MONITOR_URL: REMOTE_URL + ':' + SERVER_PORTS.MARKETS_MONITOR_PORT,
  LIVE_BOT_URL: REMOTE_URL + ':' + SERVER_PORTS.LIVE_BOT_PORT,
  NOTIFICATIONS_URL: REMOTE_URL + ':' + SERVER_PORTS.NOTIFICATIONS_SYSTEM_PORT,
};

PROJECT_URLS.CENTRALIZATION_URL = LICENSE_SERVER_URL;

export const NOTIFICATIONS_ENDPOINTS = {
  HEALTH: '/health',
  SEND_NOTIFICATION: '/notify',
};

export const NOTIFICATIONS_URLS = {
  ROOT: PROJECT_URLS.NOTIFICATIONS_URL,
  HEALTH: PROJECT_URLS.NOTIFICATIONS_URL + NOTIFICATIONS_ENDPOINTS.HEALTH,
  SEND_NOTIFICATION:
    PROJECT_URLS.NOTIFICATIONS_URL + NOTIFICATIONS_ENDPOINTS.SEND_NOTIFICATION,
};

export const DATA_FILLERS_ENDPOINTS = {
  HEALTH: '/health',
  CLEAR_DATABASE: '/clearDB',
  FILL_ALL_HISTORICAL_DATA: '/api/fillAllHistoricalData',
  STOP_FILL: '/api/stopFill',
  FILL_HISTORICAL_DATA: '/api/fillHistoricalData',
  FILL_WEBSOCKET: '/api/fillWs',
};

export const DATA_FILLER_URLS = {
  ROOT: PROJECT_URLS.DATA_FILLERS_URL,
  HEALTH: PROJECT_URLS.DATA_FILLERS_URL + DATA_FILLERS_ENDPOINTS.HEALTH,
  CLEAR_DATABASE:
    PROJECT_URLS.DATA_FILLERS_URL + DATA_FILLERS_ENDPOINTS.CLEAR_DATABASE,
  FILL_WEBSOCKET:
    PROJECT_URLS.DATA_FILLERS_URL + DATA_FILLERS_ENDPOINTS.FILL_WEBSOCKET,
  FILL_ALL_HISTORICAL_DATA:
    PROJECT_URLS.DATA_FILLERS_URL +
    DATA_FILLERS_ENDPOINTS.FILL_ALL_HISTORICAL_DATA,
  FILL_HISTORICAL_DATA:
    PROJECT_URLS.DATA_FILLERS_URL + DATA_FILLERS_ENDPOINTS.FILL_HISTORICAL_DATA,
};

export const MARKETS_MONITOR_ENDPOINTS = {
  HEALTH: '/health',
  START: '/startMonitoring',
  STOP: '/stopMonitoring',
  RECONNECT_BROKER: '/reconnect',
};

export const MARKETS_MONITOR_URLS = {
  ROOT: PROJECT_URLS.MARKETS_MONITOR_URL,
  HEALTH: PROJECT_URLS.MARKETS_MONITOR_URL + MARKETS_MONITOR_ENDPOINTS.HEALTH,
  CONNECTION_WEBSOCKET:
    REMOTE_WSS_URL + ':' + SERVER_PORTS.MARKETS_MONITOR_PORT + '/ws',
  START_MONITORING:
    PROJECT_URLS.MARKETS_MONITOR_URL + MARKETS_MONITOR_ENDPOINTS.START,
  STOP_MONITORING:
    PROJECT_URLS.MARKETS_MONITOR_URL + MARKETS_MONITOR_ENDPOINTS.STOP,
  RECONNECT_BROKER:
    PROJECT_URLS.MARKETS_MONITOR_URL +
    MARKETS_MONITOR_ENDPOINTS.RECONNECT_BROKER,
};

export const CENTRALIZATION_ENDPOINTS = {
  USERS: '/users',
  PRODUCT_CATALOG_ENDPOINT: '/products',
  GITHUB_TOKEN: '/get-github-token',
  STRIPE_CONFIG: '/config',
  STRIPE_CHECKOUT_SESSION: '/create_checkout_session',
  STRIPE_CHECK_SUBSCRIPTION: '/check-subscription-status',
  STRIPE_CANCEL_SUBSCRIPTION: '/cancel-subscription',
};

export const CENTRALIZATION_API_URLS = {
  USERS: PROJECT_URLS.CENTRALIZATION_URL + CENTRALIZATION_ENDPOINTS.USERS,
  PRODUCTS_CATALOG:
    PROJECT_URLS.CENTRALIZATION_URL +
    CENTRALIZATION_ENDPOINTS.PRODUCT_CATALOG_ENDPOINT,
  GITHUB_TOKEN:
    PROJECT_URLS.CENTRALIZATION_URL + CENTRALIZATION_ENDPOINTS.GITHUB_TOKEN,
  STRIPE_CONFIG:
    PROJECT_URLS.CENTRALIZATION_URL + CENTRALIZATION_ENDPOINTS.STRIPE_CONFIG,
  STRIPE_CHECKOUT_SESSION:
    PROJECT_URLS.CENTRALIZATION_URL +
    CENTRALIZATION_ENDPOINTS.STRIPE_CHECKOUT_SESSION,
  STRIPE_CHECK_SUBSCRIPTION:
    PROJECT_URLS.CENTRALIZATION_URL +
    CENTRALIZATION_ENDPOINTS.STRIPE_CHECK_SUBSCRIPTION,
  STRIPE_CANCEL_SUBSCRIPTION:
    PROJECT_URLS.CENTRALIZATION_URL +
    CENTRALIZATION_ENDPOINTS.STRIPE_CANCEL_SUBSCRIPTION,
};
