name: Build and Release ASAR File

on:
  push:
    branches:
      - 'bt/app'
      - 'release/*'
      - 'feature/asar-build'

jobs:
  build_asar:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          yarn install
          yarn global add @quasar/cli

      - name: Build Quasar Electron app
        run: |
          yarn quasar build -m electron

      - name: Copy ASAR File
        run: |
          mkdir -p dist/asar_files
          cp dist/electron/Packaged/Quasar\ App-darwin-arm64/Quasar\ App.app/Contents/Resources/app.asar dist/asar_files/app.asar

      - name: Upload ASAR File Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-asar
          path: dist/asar_files/app.asar

  release:
    needs: build_asar
    runs-on: ubuntu-latest
    if: github.ref_name == 'bt/app'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download ASAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-asar
          path: ./artifacts/asar

      # Get and increment the latest tag version
      - name: Increment Version Tag
        id: tag_version
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          if [[ -z "$latest_tag" ]]; then
            new_tag="v1.0.0"
          else
            IFS='.' read -r major minor patch <<<"${latest_tag#v}"
            new_tag="v$major.$minor.$((patch + 1))"
          fi
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV
          git tag $new_tag
          git push origin $new_tag

      # Create a GitHub release with the new tag
      - name: Create GitHub Release for ASAR
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.new_tag }}
          name: ASAR Release - ${{ env.new_tag }}
          draft: false
          prerelease: false
          files: ./artifacts/asar/app.asar
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_PUSH }}
