name: Build Electron App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          yarn install
          yarn global add @quasar/cli

      # Step 4: Build the Electron app with Quasar
      - name: Build Quasar Electron app
        run: |
          yarn quasar build -m electron

      # Step 5: Remove the Unpacked folder (only on macOS)
      - name: Remove Unpacked folder (macOS only)
        if: matrix.os == 'macos-latest'
        run: |
          rm -rf dist/electron/Unpacked

      # Step 6: Copy .asar file for later upload (on macOS only, since it's the same across platforms)
      - name: Copy ASAR file
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p dist/asar_files
          cp dist/electron/Packaged/Quasar\ App-darwin-arm64/Quasar\ App.app/Contents/Resources/app.asar dist/asar_files/app.asar

      # Step 7: Upload the build artifacts for download
      - name: Upload platform-specific build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-app-${{ matrix.os }}
          path: dist/electron/Packaged

      # Step 8: Upload the ASAR file
      - name: Upload ASAR file
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: app-asar
          path: dist/asar_files/app.asar
