name: Build and Release ASAR File

on:
  push:
    branches:
      - 'bt/app'
      - 'release/*'
      - 'feature/asar-build'

jobs:
  build_asar:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          yarn install
          yarn global add @quasar/cli

      - name: Build Quasar Electron app
        run: |
          yarn quasar build -m electron

      - name: Copy ASAR File
        run: |
          mkdir -p dist/asar_files
          cp dist/electron/Packaged/Quasar\ App-darwin-arm64/Quasar\ App.app/Contents/Resources/app.asar dist/asar_files/app.asar

      - name: Check ASAR File Size and SHA256
        run: |
          du -sh dist/asar_files/app.asar
          shasum -a 256 dist/asar_files/app.asar

      - name: Upload ASAR File Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-asar
          path: dist/asar_files/app.asar

  release:
    needs: build_asar
    runs-on: ubuntu-latest
    if: github.ref_name == 'bt/app'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download ASAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-asar
          path: ./artifacts/asar

      - name: Compress ASAR File
        run: |
          cd ./artifacts/asar
          zip app-asar.zip app.asar  # Compress ASAR file into a .zip file
          du -sh app-asar.zip  # Check the size of the compressed file

      - name: Calculate Next Tag
        id: calculate_tag
        run: |
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          if [[ -z "$latest_tag" ]]; then
            echo "v0.1.0" > NEXT_TAG
          else
            major=$(echo "$latest_tag" | cut -d. -f1)
            minor=$(echo "$latest_tag" | cut -d. -f2)
            patch=$(echo "$latest_tag" | cut -d. -f3)
            next_patch=$((patch + 1))
            echo "$major.$minor.$next_patch" > NEXT_TAG
          fi
          echo "NEXT_TAG=$(cat NEXT_TAG)" >> $GITHUB_ENV

      - name: Push New Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$NEXT_TAG"
          git push origin "$NEXT_TAG"

      # Create a GitHub release with the compressed ASAR file
      - name: Create GitHub Release for ASAR
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEXT_TAG }}
          name: ASAR Release - ${{ env.NEXT_TAG }}
          draft: false
          prerelease: false
          files: ./artifacts/asar/app-asar.zip # Upload the compressed file
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_PUSH }}
